FROM python:3.8
WORKDIR /bbc-news-classification-mlops
COPY requirements.txt ./requirements.txt
RUN pip install -r requirements.txt
RUN python -m nltk.downloader stopwords
RUN python -m nltk.downloader wordnet
RUN python -m nltk.downloader punkt
RUN python -m nltk.download('averaged_perceptron_tagger')
RUN python -m nltk.download('omw-1.4')
EXPOSE 8501
COPY . /bbc-news-classification-mlops
ENTRYPOINT ["streamlit", "run"]
CMD ["application.py"]